#!/usr/bin/env python3
"""Emit the Smart Guitar CAD dimension sheet from the governed records.

Dev Order: SMART-GUITAR-CAVITY-GEOMETRY-1

Written for someone starting a CAD model on a design that is not finished. The
organising idea is CONFIDENCE, not subject: figures are grouped by how much
weight they will bear, so a modeller knows which to cut geometry from, which to
drive off parameters, and which cannot be drawn yet at all.

    python scripts/export_cad_dimensions.py

Everything is read from the governed records. Nothing is transcribed, so a
figure that moves in a fixture moves here on the next run. The sheet this
replaced claimed to be generated while being hand-written, and by the time
anyone checked it carried a 162 mm one-piece pod from before the split and a
pocket for a part no longer in the design.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
GEOMETRY = ROOT / "fixtures" / "geometry" / "smart_guitar_cavity_geometry_v1.json"
REGISTER = ROOT / "fixtures" / "geometry" / "smart_guitar_component_register_v1.json"
BRIDGE = ROOT / "fixtures" / "geometry" / "headless_bridge_routing_v1.json"
TOOLING = ROOT / "fixtures" / "geometry" / "routing_tooling_v1.json"
BAY = ROOT / "fixtures" / "geometry" / "smart_guitar_electronics_bay_v1.json"
PRODUCT = ROOT / "fixtures" / "products" / "smart_guitar_v1.json"
OUT = ROOT / "docs" / "geometry" / "SMART_GUITAR_CAD_DIMENSIONS.md"


def _module(name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render() -> str:
    geometry = json.loads(GEOMETRY.read_text(encoding="utf-8"))
    register = json.loads(REGISTER.read_text(encoding="utf-8"))
    bridge = json.loads(BRIDGE.read_text(encoding="utf-8"))
    tooling = json.loads(TOOLING.read_text(encoding="utf-8"))
    bay = json.loads(BAY.read_text(encoding="utf-8"))
    product = json.loads(PRODUCT.read_text(encoding="utf-8"))
    solver = _module("solve_khaya_pocket_layout")
    dxf = solver.load_export_module()

    con = product["construction"]
    series = product["series"][0]
    body = geometry["body"]
    block = bridge["derived_block"]
    open_conflicts = [c for c in geometry["conflicts"] if c["status"] == "unresolved"]

    out: list[str] = []
    w = out.append

    w("# Smart Guitar — CAD dimension sheet")
    w("")
    w("Generated by `scripts/export_cad_dimensions.py` from the governed records.")
    w("Do not edit this file — edit the records and regenerate.")
    w("")
    w("All dimensions **mm**. Origin: body **top edge** for `y`, instrument")
    w("**centreline** for `x`, **+x toward treble**.")
    w("")
    w("**The design is not finished.** Figures are grouped by how much weight they")
    w("bear, so nothing here has to be taken on trust:")
    w("")
    w("| Section | What it means |")
    w("|---|---|")
    w("| 1 · Fixed | Ruled or corroborated. Cut geometry from these. |")
    w("| 2 · Parametric | Right today, derived from a part. Drive off variables. |")
    w("| 3 · Routing schedule | Every cut, by face, with depths. |")
    w("| 4 · Not established | Cannot be drawn yet. Listed so nothing gets invented. |")
    w("")
    w("---")
    w("")

    w("## 1. Fixed — cut geometry from these")
    w("")
    w("| Dimension | Value | Basis |")
    w("|---|---:|---|")
    w(f"| Body length | **{con['body_length_mm']}** | Official CAD, ruled |")
    w(f"| Body width, maximum | **{con['body_width_mm']}** | Outline aspect, corroborated "
      "three ways |")
    w(f"| Body thickness | **{con['body_thickness_mm']}** | Ruled after four web failures |")
    w(f"| Scale length | **{con['scale_length_mm']}** | Product record |")
    w(f"| Frets | **{con['fret_count']}** | Ruled — standard, not 25 |")
    w(f"| Strings | **{con['string_count']}** | |")
    w(f"| Bass overhang past treble | **{dxf.DOCUMENTED_BASS_OVERHANG_MM}** | Trace metadata; "
      "this is what fixes `x = 0` |")
    w(f"| Rim minimum, cavity to outline | **{solver.RIM_MIN}** | sg-spec |")
    w(f"| Web and floor minimum | **{solver.MIN_WEB}** | Ruled |")
    w("")
    w(f"Neck joint **{con['neck_joint']}** · headstock **{series['headstock']}** · nut "
      f"**{series['nut_type']}** · body **{con['body_type']}**.")
    w("")

    w("## 2. Parametric — right today, derived from a part")
    w("")
    w("Each figure is computed from a component or a vendor envelope, so it is")
    w("correct until that component changes. Drive them off variables rather than")
    w("drawing them as literals.")
    w("")
    w("### 2.1 Components")
    w("")
    w("| Part | L | W | H | Standoff | Lid clr |")
    w("|---|---:|---:|---:|---:|---:|")
    for c in register["components"]:
        w(f"| {c['display_name']} | {c['length_mm']} | {c['width_mm']} | {c['height_mm']} "
          f"| {c['standoff_mm']} | {c['lid_clearance_mm']} |")
    w("")
    w("### 2.2 Cavities — sizes only")
    w("")
    w("`depth = standoff + height + lid clearance`; footprint from the parts plus")
    w("margins. Cut depths and faces are in **section 3**; positions are in")
    w("**section 4** and are not settled.")
    w("")
    w("| Cavity | L | W | D |")
    w("|---|---:|---:|---:|")
    for c in geometry["cavities"]:
        w(f"| `{c['cavity_id']}` | {c['derived_length_mm']} | {c['derived_width_mm']} "
          f"| {c['derived_depth_mm']} |")
    w("")
    w(f"Deepest cavity plus floor needs **{body['required_thickness_mm']}** of the "
      f"**{con['body_thickness_mm']}** blank, governed by `{body['governing_cavity_id']}` — "
      f"margin **{body['margin_mm']}**.")
    w("")
    w("### 2.3 Bridge block — the solid it needs")
    w("")
    w("A headless terminates all string tension here, so this is solid material")
    w("through the full depth, not a pocket over a hollow.")
    w("")
    w("| | Value |")
    w("|---|---:|")
    w(f"| Rout envelope | **{block['rout_width_mm']} × {block['rout_length_mm']}** |")
    w(f"| Rout depth, maximum | **{block['max_depth_mm']}** |")
    w(f"| Block, in plan | **{block['block_width_mm']} × {block['block_length_mm']}** |")
    w(f"| Solid depth required | **{block['required_solid_depth_mm']}** |")
    w(f"| Remaining below | {block['remaining_below_mm']} — {block['verdict']} |")
    w("")
    w(f"Worst case across {len(bridge['candidates'])} candidate units, governed by "
      f"`{block['governing_unit_id']}`, plus {bridge['screw_margin_mm']} screw margin per side.")
    w("")
    w("| Unit | Rout W × L | Depths | Measured from |")
    w("|---|---:|---|---|")
    for c in bridge["candidates"]:
        levels = " / ".join(str(v) for v in c["levels"])
        w(f"| {c['display_name']} | {c['rout_width_mm']} × {c['rout_length_mm']} | {levels} "
          f"| {c['measured_from']} |")
    w("")
    w("> Both are **hand measurements of production guitars**, not vendor CAD, and")
    w("> the screw margin is an engineering estimate. Do not cut to them as though")
    w("> they were toleranced drawings.")
    w("")

    w("## 3. Routing schedule — what actually gets cut")
    w("")
    w("Every rout in the instrument, by face. Sizes are settled where shown;")
    w("**positions are not** — see section 4.")
    w("")
    reg, bd = bay["region"], bay["derived"]
    w(f"### 3.0 Electronics bay — {reg['width_mm']} × {reg['height_mm']}")
    w("")
    w(f"{reg['datum']}")
    w("")
    w("Coordinates below are **local to the bay**. Positioning the bay on the")
    w("outline is one transform applied to all four items at once.")
    w("")
    w("| Item | x | y | L | W | D |")
    w("|---|---:|---:|---:|---:|---:|")
    for it in bay["placements"]:
        w(f"| `{it['item_id']}` | {it['x_mm']} | {it['y_mm']} | {it['width_mm']} "
          f"| {it['height_mm']} | {it['depth_mm']} |")
    w("")
    w(f"**{bd['width_used_mm']} × {bd['height_used_mm']} used of "
      f"{reg['width_mm']} × {reg['height_mm']}** — {bd['width_spare_mm']} spare across, "
      f"{bd['height_spare_mm']} down.")
    w("")
    w("> The **GPIO ribbon**, not the bay, holds the Pi and the analog board")
    w("> 7.0 mm apart: the headers sit at each board's centre, so a 100 mm part")
    w("> at 10% slack allows 90.0 mm of run. The bay has room for 44 mm with a")
    w("> 150 mm ribbon. If the EMC measurement demands distance, cable length is")
    w("> the cheapest lever in the instrument.")
    w("")
    w("### 3.1 Back face — electronics")
    w("")
    w("Cut from the REAR. Depths are from the rear surface.")
    w("")
    radii = {c["cavity_id"]: c for c in tooling["cavities"]}
    w("| Rout | L | W | D | Corner r | Holds |")
    w("|---|---:|---:|---:|---:|---|")
    holds = {
        "POD_PI": "Pi 5 on 6.0 standoffs",
        "POD_HAT": "audio front-end board on 6.0 standoffs",
        "BATTERY_CHAMBER": "pack + BMS",
        "WIRE_CHANNEL_PI_HAT": "GPIO ribbon between the two pods",
    }
    for c in geometry["cavities"]:
        t = radii[c["cavity_id"]]
        w(f"| `{c['cavity_id']}` | {c['derived_length_mm']} | {c['derived_width_mm']} "
          f"| {c['derived_depth_mm']} | {t['corner_radius_mm']} "
          f"| {holds.get(c['cavity_id'], '')} |")
    w("")
    w("The channel is a **shallow surface groove**, not a pocket: 5.0 deep against")
    w("the pods' 27.0 and 33.0. It only has to clear a 2.0 mm ribbon plus dressing.")
    w("")
    w("### 3.2 Front face — bridge")
    w("")
    w("The deepest and most consequential rout in the instrument, and the only one")
    w("that must land on solid material.")
    w("")
    for c in bridge["candidates"]:
        w(f"**{c['display_name']}** — {c['rout_width_mm']} × {c['rout_length_mm']}, "
          f"max depth {c['max_depth_mm']}")
        w("")
        w("| Level | Depth |")
        w("|---|---:|")
        for i, lvl in enumerate(c["levels"], 1):
            w(f"| {i} | {lvl} |")
        if c.get("inner_pocket_width_mm"):
            w(f"| Inner pocket | {c['inner_pocket_width_mm']} × "
              f"{c['inner_pocket_length_mm']}, on the string centreline |")
        w("")
        w(f"*{c['note']}*")
        w("")
    w("### 3.3 Front face — not established")
    w("")
    w("| Rout | Status |")
    w("|---|---|")
    w("| Pickup route | Two sources: **82.0 × 38.0 × 19.05, r4.0** and "
      "**92.0 × 40.0 × 19.0, r3.0**. Both assume humbuckers; pickup type is open. |")
    w("| Neck pocket | Sources disagree on size and position. |")
    w("| Control cavity | Seen in the render under a cover plate; never dimensioned. |")
    w("| Cover-plate rebates | Not specified for any cavity. |")
    w("")
    d = tooling["derived"]
    deep = [c for c in tooling["cavities"] if c["reach_class"] != "standard"]
    w(f"### 3.4 Tooling — cutter {tooling['cutter_diameter_mm']}, "
      f"radius {d['internal_corner_radius_mm']}")
    w("")
    w(f"**Finishing cutter is {tooling['cutter_diameter_mm']} mm**, owner-specified. Every")
    w(f"internal corner in 3.1 is therefore **r{d['internal_corner_radius_mm']}** — derived,")
    w("not chosen per pocket. Change the cutter and every radius moves with it.")
    w("")
    w("| | Value |")
    w("|---|---:|")
    w(f"| Cutter diameter | **{tooling['cutter_diameter_mm']}** |")
    w(f"| Internal corner radius | **{d['internal_corner_radius_mm']}** |")
    w(f"| Square-corner intrusion, diagonal | {d['square_corner_intrusion_diagonal_mm']} |")
    w(f"| — per axis | {d['square_corner_intrusion_per_axis_mm']} |")
    w(f"| Clearance carried per side | {tooling['part_clearance_per_side_mm']} |")
    w(f"| Verdict | **{d['clearance_verdict']}** |")
    w("")
    w("A square PCB corner cannot reach into a radiused pocket corner, but the")
    w(f"leftover material only reaches {d['square_corner_intrusion_per_axis_mm']} per axis "
      f"against {tooling['part_clearance_per_side_mm']} of clearance.")
    w("**No corner relief is needed and none should be added.**")
    w("")
    if deep:
        w("**Reach is the real constraint, not radius.**")
        w("")
        w("| Rout | Depth | Cutter needed |")
        w("|---|---:|---|")
        for c in tooling["cavities"]:
            need = {"standard": "stock", "long_series": "**long series**",
                    "beyond_long_series": "**beyond long series**"}[c["reach_class"]]
            w(f"| `{c['cavity_id']}` | {c['depth_mm']} | {need} |")
        w("")
        w(f"Stock flute length at this diameter is about {tooling['standard_cut_length_mm']}, "
          f"long series about {tooling['long_series_cut_length_mm']}. "
          f"{' and '.join('`' + c['cavity_id'] + '`' for c in deep)} exceed the first.")
        w("A 6.35 tool at that stickout deflects, so rough with something larger and")
        w("leave the 6.35 a finishing pass.")
        w("")
    w("The bridge rout is **excluded** — its radii come from the vendor drawing,")
    w("which gives R6 for the TransTrem. A casting sits in its own designed")
    w("pocket, not in whatever the shop's cutter leaves.")
    w("")

    w("## 4. Not established — cannot be drawn yet")
    w("")
    w("Listed so a modeller does not invent them. Each needs a decision or a")
    w("measurement, not a calculation.")
    w("")
    w("| What | Why it is open |")
    w("|---|---|")
    w("| **Body outline curve** | No trustworthy source. The traced outline is stale — "
      "four voids where the design has three. The `ai_v3` SVG is outline only and 2.3% "
      "different in aspect. Length, width and thickness in section 1 are sound; the curve "
      "between them is not. |")
    w("| **Voids — count, shape, position** | Three per the renders: upper bass, upper "
      "treble, lower bass. No dimensioned source for any of them. |")
    w("| **Every cavity position** | Sizes in 2.2 are good. Placements were solved against "
      "the stale outline and are withdrawn. |")
    w("| **Electronics cavity position** | Visible in the back render on the lower treble "
      "side under a cover plate. Never dimensioned. |")
    w("| **Neck pocket** | Two sources disagree on size and position. |")
    w("| **Bridge unit** | Unselected — and the product record says "
      f"`{product['configuration']['bridge_type']}` while both drawings are **tremolo** "
      "units. A fixed bridge routs far shallower, so 2.3 may be over-specified. |")
    w("| **Pickup type and route** | Open upstream; route dimensions follow from it. |")
    w("| **Skin thickness, core species, finish** | Not selected. Skin thickness changes "
      "every internal depth. |")
    w("")
    w(f"{len(open_conflicts)} conflicts remain open against this geometry:")
    w("")
    for c in open_conflicts:
        w(f"- **`{c['conflict_id']}`** — {c['field']}")
    w("")

    w("## 5. Suggested modelling order")
    w("")
    w("Sequenced so nothing is drawn twice:")
    w("")
    w("1. Blank — length, width, thickness from section 1.")
    w("2. Centreline, placed using the bass overhang. This fixes `x = 0`.")
    w("3. Scale length and the fret plane. These drive the bridge station.")
    w("4. Bridge block from 3.2, positioned from the scale length. It is the only")
    w("   feature whose position follows from something already settled.")
    w("5. Stop. The outline curve and the voids come next, and neither exists yet.")
    w("")
    w("Rout sizes from 3.1 can be built as parametric bodies off to one side and")
    w("positioned later without rework.")
    w("")
    return "\n".join(out) + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
