#!/usr/bin/env python3
"""Render the audio front-end subassembly spec as a readable design brief.

Dev Order: SMART-GUITAR-CAVITY-GEOMETRY-1

The governed record is JSON so a validator can hold it against the cavity that
holds the board. That is the right storage format and the wrong handover
format, so this renders the same record as markdown for a PCB designer.

    python scripts/export_frontend_brief.py

Output goes to exports/, which is gitignored: the brief is regenerable from
the fixture, so the fixture stays the single source of truth and this file
cannot drift from it.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "fixtures" / "subassemblies" / "sg_audio_frontend_v1.json"
REGISTER = ROOT / "fixtures" / "geometry" / "smart_guitar_component_register_v1.json"
OUT = ROOT / "exports" / "subassemblies" / "SG_AUDIO_FRONTEND_DESIGN_BRIEF.md"

CRITICALITY_LABEL = {
    "shippable_blocker": "**BLOCKER**",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}


def render(spec: dict, register: dict) -> str:
    env = spec["envelope"]
    ff = spec["form_factor"]
    board = next(
        (c for c in register["components"] if c["component_id"] == spec["component_id"]),
        None,
    )

    out: list[str] = []
    w = out.append

    w(f"# {spec['subassembly_name']} — design brief")
    w("")
    w(f"`{spec['spec_id']}` · status **{spec['status']}** · all dimensions **mm**")
    w("")
    w("> Generated from the governed record at")
    w(f"> `{SPEC.relative_to(ROOT).as_posix()}`. Do not edit this file — edit the")
    w("> record and regenerate, or the envelope will drift from the cavity that")
    w("> holds the board.")
    w("")
    w("## Scope")
    w("")
    w("This brief carries the **mechanical envelope, system interfaces and")
    w("behavioural requirements** that come from the instrument. It deliberately")
    w("does not specify circuit topology, part numbers or component values —")
    w("those are yours to choose against these constraints.")
    w("")

    w("## 1. Form factor")
    w("")
    w(f"**{ff['standard']}**")
    w("")
    w(f"- Mounting: {ff['mounting']}")
    w(f"- {ff['stacking']}")
    w("")
    w(f"> {ff['authority_note']}")
    w("")

    w("## 2. Mechanical envelope")
    w("")
    w("| | mm |")
    w("|---|---:|")
    for key, label in (
        ("board_length_mm", "Board length"),
        ("board_width_mm", "Board width"),
        ("pcb_thickness_mm", "PCB thickness"),
        ("assembly_height_target_mm", "Assembly height — **target**"),
        ("assembly_height_max_mm", "Assembly height — hard ceiling"),
        ("bottom_side_max_mm", "Bottom-side components — max"),
    ):
        w(f"| {label} | {env[key]} |")
    w("")
    w(env["derivation"])
    w("")
    if board is not None:
        w(f"The pocket holding this board derives from these numbers: standoff "
          f"{board['standoff_mm']}, lid clearance {board['lid_clearance_mm']}, "
          f"{board['margin_length_mm']} clearance per side.")
        w("")

    el = spec["electrical"]
    w("## 3. Electrical envelope")
    w("")
    w(f"> **Every figure in this section is proposed, not confirmed.** "
      f"{el['provenance']['confidence'].upper()} — "
      f"{el['provenance']['source'].replace('_', ' ')}. Confirm before pricing against them.")
    w("")
    pa = el["power_architecture"]
    w(f"**Power architecture — `{pa['mode']}`.** {pa['rationale']}")
    w("")
    w("| | |")
    w("|---|---:|")
    sup = el["supply"]
    w(f"| Supply input, nominal | {sup['input_nominal_v']} V |")
    w(f"| Supply input, range | {sup['input_min_v']} – {sup['input_max_v']} V |")
    w(f"| Quiescent draw, max | {sup['quiescent_max_ma']} mA |")
    w(f"| Peak draw, max | {sup['peak_max_ma']} mA |")
    au = el["audio"]
    w(f"| Sample rate, primary | {au['sample_rate_primary_khz']} kHz |")
    w(f"| Sample rate, capable | {au['sample_rate_capable_khz']} kHz |")
    w(f"| Bit depth | {au['bit_depth']} |")
    w(f"| Input full scale, min gain | {au['input_full_scale_vpp']} Vpp |")
    w(f"| Input typical program level | {au['input_typical_vpp']} Vpp |")
    pf = el["performance"]
    w(f"| ADC SNR | ≥ {pf['adc_snr_db_a_weighted']} dB A-weighted |")
    w(f"| THD+N, max | {pf['thd_n_max_pct']} % |")
    w(f"| Headphone power into 32 Ω | ≥ {pf['headphone_power_mw_into_32r']} mW |")
    th = el["thermal"]
    w(f"| Cavity ambient | {th['cavity_ambient_min_c']} – {th['cavity_ambient_max_c']} °C |")
    w(f"| Component rating, min | {th['component_rating_min_c']} °C |")
    io = el["io_provision"]
    w(f"| Switch inputs | {io['switch_inputs']} |")
    w(f"| Analog inputs | {io['analog_inputs']} |")
    w(f"| Discrete LED outputs | {io['discrete_led_outputs']} |")
    w(f"| Addressable LED channels | {io['addressable_led_channels']} |")
    w("")
    w("### How these are to be demonstrated")
    w("")
    w("A requirement without a measurement method cannot be accepted or rejected.")
    w("")
    for line in el["measurement_conditions"]:
        w(f"- {line}")
    w("")
    w(f"*{el['provenance']['note']}*")
    w("")

    w("## 4. Interfaces")
    w("")
    w("| Interface | Direction | Connection | Notes |")
    w("|---|---|---|---|")
    for i in spec["interfaces"]:
        w(f"| `{i['interface_id']}` | {i['direction']} | {i['connection']} | "
          f"{i['description']} |")
    w("")
    w("**The jacks are body-mounted, not board-mounted.** Audio interfaces are")
    w("wire-to-board so the CNC can place jacks where the player expects them,")
    w("and so board height stays low.")
    w("")

    w("## 5. Requirements")
    w("")
    blockers = [r for r in spec["requirements"] if r["criticality"] == "shippable_blocker"]
    if blockers:
        w(f"{len(blockers)} of {len(spec['requirements'])} are shippable blockers. "
          "Those are not tradeable as implementation details.")
        w("")
    for r in spec["requirements"]:
        w(f"### {r['requirement_id']} — {CRITICALITY_LABEL[r['criticality']]}")
        w("")
        w(r["requirement"])
        w("")
        w(f"*Why:* {r['rationale']}")
        w("")

    w("## 6. Operating environment")
    w("")
    for line in spec["environment"]:
        w(f"- {line}")
    w("")

    w("## 7. Certification")
    w("")
    for line in spec["certification"]:
        w(f"- {line}")
    w("")

    w("## 8. Open questions")
    w("")
    w("These are unresolved at the time of writing and may change the design.")
    w("Raise them before committing to a topology.")
    w("")
    for line in spec["open_questions"]:
        w(f"- {line}")
    w("")

    w("## 9. Context worth knowing")
    w("")
    for line in spec["notes"]:
        w(f"- {line}")
    w("")
    return "\n".join(out)


def main() -> int:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    register = json.loads(REGISTER.read_text(encoding="utf-8"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(spec, register), encoding="utf-8")

    reqs = spec["requirements"]
    blockers = sum(1 for r in reqs if r["criticality"] == "shippable_blocker")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    print(f"  {spec['spec_id']}  status {spec['status']}")
    print(f"  {len(spec['interfaces'])} interfaces, {len(reqs)} requirements "
          f"({blockers} blockers), {len(spec['open_questions'])} open questions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
