#!/usr/bin/env python3
"""Emit the Smart Guitar CAD dimension sheet from the governed records.

Dev Order: SMART-GUITAR-CAVITY-GEOMETRY-1

Written for someone starting a CAD model on a design that is not finished. The
organising idea is CONFIDENCE, not subject: figures are grouped by how much
weight they will bear, so a modeller knows which to cut geometry from, which to
drive off parameters, and which cannot be drawn yet at all.

    python scripts/export_cad_dimensions.py

Everything is read from the governed records. Nothing is transcribed, so a
figure that moves in a fixture moves here on the next run. The sheet this
replaced claimed to be generated while being hand-written, and by the time
anyone checked it carried a 162 mm one-piece pod from before the split and a
pocket for a part no longer in the design.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
GEOMETRY = ROOT / "fixtures" / "geometry" / "smart_guitar_cavity_geometry_v1.json"
REGISTER = ROOT / "fixtures" / "geometry" / "smart_guitar_component_register_v1.json"
BRIDGE = ROOT / "fixtures" / "geometry" / "headless_bridge_routing_v1.json"
PRODUCT = ROOT / "fixtures" / "products" / "smart_guitar_v1.json"
OUT = ROOT / "docs" / "geometry" / "SMART_GUITAR_CAD_DIMENSIONS.md"


def _module(name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render() -> str:
    geometry = json.loads(GEOMETRY.read_text(encoding="utf-8"))
    register = json.loads(REGISTER.read_text(encoding="utf-8"))
    bridge = json.loads(BRIDGE.read_text(encoding="utf-8"))
    product = json.loads(PRODUCT.read_text(encoding="utf-8"))
    solver = _module("solve_khaya_pocket_layout")
    dxf = solver.load_export_module()

    con = product["construction"]
    series = product["series"][0]
    body = geometry["body"]
    block = bridge["derived_block"]
    open_conflicts = [c for c in geometry["conflicts"] if c["status"] == "unresolved"]

    out: list[str] = []
    w = out.append

    w("# Smart Guitar — CAD dimension sheet")
    w("")
    w("Generated by `scripts/export_cad_dimensions.py` from the governed records.")
    w("Do not edit this file — edit the records and regenerate.")
    w("")
    w("All dimensions **mm**. Origin: body **top edge** for `y`, instrument")
    w("**centreline** for `x`, **+x toward treble**.")
    w("")
    w("**The design is not finished.** Figures are grouped by how much weight they")
    w("bear, so nothing here has to be taken on trust:")
    w("")
    w("| Section | What it means |")
    w("|---|---|")
    w("| 1 · Fixed | Ruled or corroborated. Cut geometry from these. |")
    w("| 2 · Parametric | Right today, derived from a part. Drive off variables. |")
    w("| 3 · Not established | Cannot be drawn yet. Listed so nothing gets invented. |")
    w("")
    w("---")
    w("")

    w("## 1. Fixed — cut geometry from these")
    w("")
    w("| Dimension | Value | Basis |")
    w("|---|---:|---|")
    w(f"| Body length | **{con['body_length_mm']}** | Official CAD, ruled |")
    w(f"| Body width, maximum | **{con['body_width_mm']}** | Outline aspect, corroborated "
      "three ways |")
    w(f"| Body thickness | **{con['body_thickness_mm']}** | Ruled after four web failures |")
    w(f"| Scale length | **{con['scale_length_mm']}** | Product record |")
    w(f"| Frets | **{con['fret_count']}** | Ruled — standard, not 25 |")
    w(f"| Strings | **{con['string_count']}** | |")
    w(f"| Bass overhang past treble | **{dxf.DOCUMENTED_BASS_OVERHANG_MM}** | Trace metadata; "
      "this is what fixes `x = 0` |")
    w(f"| Rim minimum, cavity to outline | **{solver.RIM_MIN}** | sg-spec |")
    w(f"| Web and floor minimum | **{solver.MIN_WEB}** | Ruled |")
    w("")
    w(f"Neck joint **{con['neck_joint']}** · headstock **{series['headstock']}** · nut "
      f"**{series['nut_type']}** · body **{con['body_type']}**.")
    w("")

    w("## 2. Parametric — right today, derived from a part")
    w("")
    w("Each figure is computed from a component or a vendor envelope, so it is")
    w("correct until that component changes. Drive them off variables rather than")
    w("drawing them as literals.")
    w("")
    w("### 2.1 Components")
    w("")
    w("| Part | L | W | H | Standoff | Lid clr |")
    w("|---|---:|---:|---:|---:|---:|")
    for c in register["components"]:
        w(f"| {c['display_name']} | {c['length_mm']} | {c['width_mm']} | {c['height_mm']} "
          f"| {c['standoff_mm']} | {c['lid_clearance_mm']} |")
    w("")
    w("### 2.2 Cavities — sizes only")
    w("")
    w("`depth = standoff + height + lid clearance`; footprint from the parts plus")
    w("margins. **Positions are in section 3** — they are not settled.")
    w("")
    w("| Cavity | L | W | D |")
    w("|---|---:|---:|---:|")
    for c in geometry["cavities"]:
        w(f"| `{c['cavity_id']}` | {c['derived_length_mm']} | {c['derived_width_mm']} "
          f"| {c['derived_depth_mm']} |")
    w("")
    w(f"Deepest cavity plus floor needs **{body['required_thickness_mm']}** of the "
      f"**{con['body_thickness_mm']}** blank, governed by `{body['governing_cavity_id']}` — "
      f"margin **{body['margin_mm']}**.")
    w("")
    w("### 2.3 Bridge block")
    w("")
    w("A headless terminates all string tension here, so this is solid material")
    w("through the full depth, not a pocket over a hollow.")
    w("")
    w("| | Value |")
    w("|---|---:|")
    w(f"| Rout envelope | **{block['rout_width_mm']} × {block['rout_length_mm']}** |")
    w(f"| Rout depth, maximum | **{block['max_depth_mm']}** |")
    w(f"| Block, in plan | **{block['block_width_mm']} × {block['block_length_mm']}** |")
    w(f"| Solid depth required | **{block['required_solid_depth_mm']}** |")
    w(f"| Remaining below | {block['remaining_below_mm']} — {block['verdict']} |")
    w("")
    w(f"Worst case across {len(bridge['candidates'])} candidate units, governed by "
      f"`{block['governing_unit_id']}`, plus {bridge['screw_margin_mm']} screw margin per side.")
    w("")
    w("| Unit | Rout W × L | Depths | Measured from |")
    w("|---|---:|---|---|")
    for c in bridge["candidates"]:
        levels = " / ".join(str(v) for v in c["levels"])
        w(f"| {c['display_name']} | {c['rout_width_mm']} × {c['rout_length_mm']} | {levels} "
          f"| {c['measured_from']} |")
    w("")
    w("> Both are **hand measurements of production guitars**, not vendor CAD, and")
    w("> the screw margin is an engineering estimate. Do not cut to them as though")
    w("> they were toleranced drawings.")
    w("")

    w("## 3. Not established — cannot be drawn yet")
    w("")
    w("Listed so a modeller does not invent them. Each needs a decision or a")
    w("measurement, not a calculation.")
    w("")
    w("| What | Why it is open |")
    w("|---|---|")
    w("| **Body outline curve** | No trustworthy source. The traced outline is stale — "
      "four voids where the design has three. The `ai_v3` SVG is outline only and 2.3% "
      "different in aspect. Length, width and thickness in section 1 are sound; the curve "
      "between them is not. |")
    w("| **Voids — count, shape, position** | Three per the renders: upper bass, upper "
      "treble, lower bass. No dimensioned source for any of them. |")
    w("| **Every cavity position** | Sizes in 2.2 are good. Placements were solved against "
      "the stale outline and are withdrawn. |")
    w("| **Electronics cavity position** | Visible in the back render on the lower treble "
      "side under a cover plate. Never dimensioned. |")
    w("| **Neck pocket** | Two sources disagree on size and position. |")
    w("| **Bridge unit** | Unselected — and the product record says "
      f"`{product['configuration']['bridge_type']}` while both drawings are **tremolo** "
      "units. A fixed bridge routs far shallower, so 2.3 may be over-specified. |")
    w("| **Pickup type and route** | Open upstream; route dimensions follow from it. |")
    w("| **Skin thickness, core species, finish** | Not selected. Skin thickness changes "
      "every internal depth. |")
    w("")
    w(f"{len(open_conflicts)} conflicts remain open against this geometry:")
    w("")
    for c in open_conflicts:
        w(f"- **`{c['conflict_id']}`** — {c['field']}")
    w("")

    w("## 4. Suggested modelling order")
    w("")
    w("Sequenced so nothing is drawn twice:")
    w("")
    w("1. Blank — length, width, thickness from section 1.")
    w("2. Centreline, placed using the bass overhang. This fixes `x = 0`.")
    w("3. Scale length and the fret plane. These drive the bridge station.")
    w("4. Bridge block from 2.3, positioned from the scale length. It is the only")
    w("   feature whose position follows from something already settled.")
    w("5. Stop. The outline curve and the voids come next, and neither exists yet.")
    w("")
    w("Cavity sizes from 2.2 can be built as parametric bodies off to one side and")
    w("positioned later without rework.")
    w("")
    return "\n".join(out) + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
