#!/usr/bin/env python3
"""Emit the Smart Guitar CAD dimension sheet from the governed records.

Dev Order: SMART-GUITAR-CAVITY-GEOMETRY-1

The sheet this replaces claimed at the top to be "generated from the governed
geometry record, not transcribed by hand". It was not — it was hand-written,
and by 2026-07-27 it carried a 162 mm one-piece pod from before the split, a
Teensy pocket for a part no longer in the design, and the superseded pod
position. A document that says it is generated and is not will be trusted
exactly as far as one that is.

    python scripts/export_cad_dimensions.py

Sizes come from the derived geometry, positions from the ruled placement in
the DXF export, and clearances are recomputed here rather than quoted, so a
number cannot survive in this sheet after the geometry that produced it moves.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
GEOMETRY = ROOT / "fixtures" / "geometry" / "smart_guitar_cavity_geometry_v1.json"
REGISTER = ROOT / "fixtures" / "geometry" / "smart_guitar_component_register_v1.json"
OUT = ROOT / "docs" / "geometry" / "SMART_GUITAR_CAD_DIMENSIONS.md"

BACK_FACE = ("POD_PI", "POD_HAT", "BATTERY")
POCKET_OF = {"POD_PI": "POD_PI", "POD_HAT": "POD_HAT", "BATTERY": "BATTERY_CHAMBER"}


def _module(name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render() -> str:
    geometry = json.loads(GEOMETRY.read_text(encoding="utf-8"))
    register = json.loads(REGISTER.read_text(encoding="utf-8"))
    dxf = _module("export_smart_guitar_dxf")
    solver = _module("solve_khaya_pocket_layout")

    cavities = {c["cavity_id"]: c for c in geometry["cavities"]}
    parts = {c["component_id"]: c for c in register["components"]}
    placed = {c[1]: c for c in dxf.CAVITIES}
    boxes = {
        label: solver.rect(row[2], row[3], row[4], row[5]) for label, row in placed.items()
    }
    outline, voids, features = solver.load_body()
    body = geometry["body"]

    out: list[str] = []
    w = out.append

    w("# Smart Guitar — CAD dimension sheet")
    w("")
    w("Generated by `scripts/export_cad_dimensions.py` from the governed records.")
    w("Do not edit this file — edit the records and regenerate.")
    w("")
    w(f"- Derived geometry: `{GEOMETRY.relative_to(ROOT).as_posix()}`")
    w(f"- Component register: `{REGISTER.relative_to(ROOT).as_posix()}`")
    w("- Placement: `CONF-POD-EMC-CLEARANCE`, re-derivable with")
    w("  `scripts/solve_khaya_pocket_layout.py`")
    w("")
    w("All dimensions **mm**. Origin: body **top edge** for `y`, instrument")
    w("**centreline** for `x`, **+x toward treble**. Cavity `y` reads as")
    w("`-y_from_top`.")
    w("")
    w("---")
    w("")

    blocking = next(
        (c for c in geometry["conflicts"]
         if c["conflict_id"] == "CONF-POD-EMC-CLEARANCE" and c["status"] == "unresolved"),
        None,
    )
    if blocking is not None:
        w("> ## DO NOT CUT FROM THIS SHEET")
        w(">")
        w("> `CONF-POD-EMC-CLEARANCE` is open. The back-face pocket positions")
        w("> in section 2 were solved against a stale void set — the design")
        w("> carries three voids, not four, and what the trace shows as a")
        w("> fourth is the electronics cavity itself. No valid placement has")
        w("> been derived since.")
        w(">")
        w("> Everything downstream of those positions — section 4 clearances,")
        w("> section 5 ribbon reach — is invalid with them. Sections 1 and 3")
        w("> are unaffected.")
        w("")

    w("## 1. Body")
    w("")
    w("| Dimension | Value |")
    w("|---|---:|")
    w(f"| Length | **{dxf.BODY_LENGTH_MM}** |")
    w(f"| Width, maximum | **{dxf.BODY_WIDTH_MM}** |")
    w(f"| Thickness | **{dxf.BODY_THICKNESS_MM}** |")
    w(f"| Required thickness | {body['required_thickness_mm']} "
      f"(governed by `{body['governing_cavity_id']}`) |")
    w(f"| Margin | {body['margin_mm']} — **{body['verdict']}** |")
    w("")
    w(f"Rim minimum {dxf.RIM_MIN_MM}, inter-cavity web minimum {solver.MIN_WEB}, "
      f"floor minimum {solver.MIN_WEB}.")
    w("")

    w("## 2. Back-face pockets")
    w("")
    w("Sizes derived from the parts they hold; positions ruled for clearance.")
    w("")
    w("| Pocket | Centre x | y from top | L | W | D | x extent | y extent |")
    w("|---|---:|---:|---:|---:|---:|---|---|")
    for label in BACK_FACE:
        _, _, cx, cy, length, width = placed[label]
        depth = cavities[POCKET_OF[label]]["derived_depth_mm"]
        w(f"| `{label}` | **{cx:.3f}** | **{cy:.1f}** | {length} | {width} | {depth} | "
          f"{cx - length / 2:.1f} .. {cx + length / 2:.1f} | "
          f"{cy - width / 2:.1f} .. {cy + width / 2:.1f} |")
    w("")

    w("## 3. Front-face features")
    w("")
    w("| Feature | Centre x | y from top | L | W |")
    w("|---|---:|---:|---:|---:|")
    for layer, label, cx, cy, length, width in dxf.CAVITIES:
        if layer != "CAV_TOP":
            continue
        w(f"| `{label}` | {cx:.1f} | {cy:.1f} | {length} | {width} |")
    w("")
    w("`NECK_POCKET`, `BRIDGE` and `CONTROL` are recovered from front_v5 with")
    w("both of its scale errors undone; they are keep-outs, not authored")
    w("geometry. `CONTROL` is disputed — see section 6.")
    w("")

    w("## 4. Clearances — the revised measurements")
    w("")
    w("Recomputed from the placement above, not quoted.")
    w("")
    w("| From | To | Clearance |")
    w("|---|---|---:|")
    route = boxes["PU_BRIDGE"]
    pairs = [
        ("POD_PI", "PU_BRIDGE", boxes["POD_PI"].distance(route)),
        ("POD_PI", "POD_HAT", boxes["POD_PI"].distance(boxes["POD_HAT"])),
        ("POD_HAT", "PU_BRIDGE", boxes["POD_HAT"].distance(route)),
        ("POD_HAT", "BATTERY", boxes["POD_HAT"].distance(boxes["BATTERY"])),
        ("POD_PI", "BATTERY", boxes["POD_PI"].distance(boxes["BATTERY"])),
        ("BATTERY", "PU_BRIDGE", boxes["BATTERY"].distance(route)),
    ]
    for a, b, value in pairs:
        w(f"| `{a}` | `{b}` | **{value:.2f}** |")
    w("")
    w("Nearest keep-out for each pocket:")
    w("")
    w("| Pocket | Rim | Nearest void | Nearest front-face feature |")
    w("|---|---:|---:|---|")
    usable = outline.buffer(-dxf.RIM_MIN_MM)
    for label in BACK_FACE:
        box = boxes[label]
        void = min(box.distance(v) for v in voids)
        name, feature = min(
            ((n, box.distance(p)) for n, p in features), key=lambda item: item[1]
        )
        w(f"| `{label}` | {'ok' if usable.contains(box) else 'BREACH'} | "
          f"{void:.2f} | `{name}` {feature:.2f} |")
    w("")

    w("## 5. GPIO ribbon")
    w("")
    span = solver._header_span(boxes["POD_PI"], boxes["POD_HAT"])
    ribbon = parts["GPIO_RIBBON"]
    w("| | Value |")
    w("|---|---:|")
    w(f"| Part length | {ribbon['length_mm']} |")
    w(f"| Required run, header to header | **{span:.2f}** |")
    w(f"| Slack | {ribbon['length_mm'] - span:.2f} "
      f"({(ribbon['length_mm'] - span) / ribbon['length_mm'] * 100:.0f}%) |")
    w("")
    w("The run is measured header to header, not edge to edge. Each 40-pin")
    w("header sits at its pocket's x centre on an x-aligned edge, so a diagonal")
    w("layout costs far more ribbon than the pocket gap suggests — see")
    w("`CONF-RIBBON-REACH`, where an earlier layout needed 118.8 of a 100 part.")
    w("")

    w("## 6. Unresolved")
    w("")
    open_conflicts = [c for c in geometry["conflicts"] if c["status"] == "unresolved"]
    w(f"{len(open_conflicts)} conflicts remain open against this geometry:")
    w("")
    for conflict in open_conflicts:
        w(f"- **`{conflict['conflict_id']}`** — {conflict['field']}")
    w("")
    return "\n".join(out) + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
